(define-module (guile-dmenu codex)
  #:use-module (guile-dmenu graphics)
  #:use-module (guile-dmenu menu)
  #:export (call-with-codex-presentation))

(define (rgb value)
  (parse-hex-color value))

(define (call-with-codex-presentation thunk)
  "Call THUNK with presentation defaults suited to Codex question dialogs."
  (parameterize ((menu-width 760)
                 (menu-padding 6)
                 (menu-max-options 6)
                 (background-color (rgb "#f6f8fa"))
                 (foreground-color (rgb "#24292f"))
                 (highlight-background-color (rgb "#dbeafe"))
                 (highlight-foreground-color (rgb "#0f172a"))
                 (filter-background-color (rgb "#ffffff"))
                 (filter-foreground-color (rgb "#24292f"))
                 (cursor-color (rgb "#0969da"))
                 (title-background-color (rgb "#0969da"))
                 (title-foreground-color (rgb "#ffffff"))
                 (alt-background-color (rgb "#ffffff"))
                 (alt-foreground-color (rgb "#24292f"))
                 (border-color (rgb "#d0d7de"))
                 (border-width 1)
                 (line-height 30)
                 (fixed-height? #f)
                 (prefix-text "› "))
    (thunk)))
