(define-module (guile-dmenu codex)
  #:use-module (guile-dmenu graphics)
  #:use-module (guile-dmenu menu)
  #:export (call-with-codex-presentation))

(define (rgb value)
  (parse-hex-color value))

(define (call-with-codex-presentation thunk)
  "Call THUNK with presentation defaults suited to Codex question dialogs."
  (parameterize ((menu-width 760)
                 (menu-padding 6)
                 (menu-max-options 6)
                 (background-color (rgb "#161b22"))
                 (foreground-color (rgb "#c9d1d9"))
                 (highlight-background-color (rgb "#2d333b"))
                 (highlight-foreground-color (rgb "#ffffff"))
                 (filter-background-color (rgb "#0d1117"))
                 (filter-foreground-color (rgb "#e6edf3"))
                 (cursor-color (rgb "#58a6ff"))
                 (title-background-color (rgb "#1f6feb"))
                 (title-foreground-color (rgb "#ffffff"))
                 (alt-background-color (rgb "#1c2128"))
                 (alt-foreground-color (rgb "#c9d1d9"))
                 (border-color (rgb "#30363d"))
                 (border-width 1)
                 (line-height 30)
                 (fixed-height? #f)
                 (prefix-text "› "))
    (thunk)))
