(define-module (guile-dmenu codex)
  #:use-module (guile-dmenu graphics)
  #:use-module (guile-dmenu menu)
  #:export (call-with-codex-presentation))

(define (rgb value)
  (parse-hex-color value))

(define (call-with-codex-presentation thunk)
  "Call THUNK with presentation defaults suited to Codex question dialogs."
  (parameterize ((menu-width 900)
                 (menu-padding 8)
                 (menu-max-options 6)
                 (background-color (rgb "#0d1117"))
                 (foreground-color (rgb "#f0f6fc"))
                 (highlight-background-color (rgb "#1f6feb"))
                 (highlight-foreground-color (rgb "#ffffff"))
                 (filter-background-color (rgb "#161b22"))
                 (filter-foreground-color (rgb "#f0f6fc"))
                 (cursor-color (rgb "#58a6ff"))
                 (title-background-color (rgb "#1f6feb"))
                 (title-foreground-color (rgb "#ffffff"))
                 (alt-background-color (rgb "#161b22"))
                 (alt-foreground-color (rgb "#f0f6fc"))
                 ;; Match Sway's default focused-window border.  The active
                 ;; Sway configuration does not override client.focused.
                 (border-color (rgb "#4c7899"))
                 (border-width 2)
                 (line-height 36)
                 (fixed-height? #f)
                 (input-line-wrapping? #t)
                 (prefix-text "› "))
    (thunk)))
