#!/usr/bin/env guile
!#
(use-modules (guile-dmenu startup)
             (guile-dmenu menu)
             (guile-dmenu graphics)
             (guile-dmenu filter)
             (ice-9 getopt-long)
             (ice-9 match)
             (ice-9 rdelim)
             (srfi srfi-2))

(report-startup-phase! 'modules-loaded)

(define option-spec
  '((prompt (single-char #\p) (value #t))
    (list (single-char #\l) (value #t))
    (wrap (single-char #\w) (value #f))
    (prefix (single-char #\P) (value #t))
    (border (single-char #\B) (value #t))
    (fixed-height (value #f)) (line-height (value #t))
    (input-wrap (value #f))
    (message (value #t)) (no-input (value #f)) (timeout (value #t))
    (nb (value #t)) (nf (value #t)) (hb (value #t)) (hf (value #t))
    (fb (value #t)) (ff (value #t)) (cb (value #t)) (tb (value #t))
    (tf (value #t)) (ab (value #t)) (af (value #t)) (bdr (value #t))))

(define (read-stdin)
  (let loop ((line (read-line)) (items '()))
    (if (eof-object? line) (reverse items)
        (loop (read-line) (cons line items)))))

(define colors
  (list (cons 'nb background-color) (cons 'nf foreground-color)
        (cons 'hb highlight-background-color) (cons 'hf highlight-foreground-color)
        (cons 'fb filter-background-color) (cons 'ff filter-foreground-color)
        (cons 'cb cursor-color) (cons 'tb title-background-color)
        (cons 'tf title-foreground-color) (cons 'ab alt-background-color)
        (cons 'af alt-foreground-color) (cons 'bdr border-color)))

(define (positive-number value)
  (and value (let ((n (string->number value))) (and n (> n 0) n))))

(let* ((opts (getopt-long (command-line) option-spec))
       (prompt (or (option-ref opts 'prompt #f) "dmenu: ")))
  (for-each (match-lambda ((name . parameter)
                           (and=> (option-ref opts name #f)
                                  (lambda (hex) (parameter (parse-hex-color hex))))))
            colors)
  (and=> (option-ref opts 'list #f)
         (lambda (n) (menu-max-options (string->number n))))
  (and=> (option-ref opts 'border #f)
         (lambda (n) (border-width (string->number n))))
  (and=> (option-ref opts 'line-height #f)
         (lambda (n) (line-height (string->number n))))
  (and=> (option-ref opts 'prefix #f) prefix-text)
  (when (option-ref opts 'wrap #f) (wrap-navigation? #t))
  (when (option-ref opts 'fixed-height #f) (fixed-height? #t))
  (when (option-ref opts 'input-wrap #f) (input-line-wrapping? #t))
  (let ((collection (read-stdin)))
    (report-startup-phase! 'input-ingested)
    (let ((answer (completing-read prompt collection
                                   #:selection-mode 'menu
                                   #:message (option-ref opts 'message #f)
                                   #:input-enabled? (not (option-ref opts 'no-input #f))
                                   #:timeout (positive-number
                                              (option-ref opts 'timeout #f)))))
      (if answer
          (begin (display answer) (newline) (primitive-exit 0))
          (primitive-exit 1)))))
